<a href="https://colab.research.google.com/github/MadhuraTonpe165/InClassLiveCodingBooks/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Upload Octane.csv file from Session documents or google drive

In [ ]:
#Importing important Libraries
import numpy as np
import pandas as pd

In [ ]:
#Importing the data
df = pd.read_csv('Octane.csv')
df.head()
# head() function is going to give us firsy 5 roes of the dataframe

   Sample  Material1  Material2  Material3  Condition  Octane
0       1      55.33       1.72         54    1.66219   92.19
1       2      59.13       1.20         53    1.58399   92.74
2       3      57.39       1.42         55    1.61731   91.88
3       4      56.43       1.78         55    1.66228   92.80
4       5      55.98       1.58         54    1.63195   92.56

In [ ]:
# getting first 7 rows
df.head(7)

   Sample  Material1  Material2  Material3  Condition  Octane
0       1      55.33       1.72         54    1.66219   92.19
1       2      59.13       1.20         53    1.58399   92.74
2       3      57.39       1.42         55    1.61731   91.88
3       4      56.43       1.78         55    1.66228   92.80
4       5      55.98       1.58         54    1.63195   92.56
5       6      56.16       2.12         56    1.68034   92.61
6       7      54.85       1.17         54    1.58206   92.33

In [ ]:
# Getting the datatype
print('Type :', type(df))

Type : <class 'pandas.core.frame.DataFrame'>

In [ ]:
# Getting shape of the dataframe
print('shape :', df.shape)
print('Rows :', df.shape[0])
print('Column :', df.shape[1])

shape : (82, 6)
Rows : 82
Column 6

In [ ]:
# Getting an idea about the data types of the coulmns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Sample     82 non-null     int64
 1   Material1  82 non-null     float64
 2   Material2  82 non-null     float64
 3   Material3  82 non-null     int64
 4   Condition  82 non-null     float64
 5   Octane     82 non-null     float64
dtypes: float64(4), int64(2)
memory usage: 4.0 KB

In [ ]:
#df.info provided overall details about the dataframe

In [ ]:
# Getting an idea about the data types
df.dtypes

Sample         int64
Material1    float64
Material2    float64
Material3      int64
Condition    float64
Octane       float64
dtype: object

In [ ]:
# Getting an idea baout the Duplicates in data
df.duplicated().sum()

0

In [ ]:
# provided the confirmation for each row with boolean value if its duplicate or not
df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
77    False
78    False
79    False
80    False
81    False
Length: 82, dtype: bool

In [ ]:
# 0 means that there are no duplicates in data

In [ ]:
# Getting an idea about the Null Values
df.isnull().sum().any()

False

In [ ]:
# False means that there are no NULL values in the data

In [ ]:
# Getting cloumnwise sum of NULL values
df.isnull().sum()

Sample       0
Material1    0
Material2    0
Material3    0
Condition    0
Octane       0
dtype: int64

In [ ]:
# Getting statistical properties of the data
print('Mean of Material1 :', df['Material1'].mean())
print('Mode of Material1 :', df['Material1'].mode()[0])
print('Median of Material1 :', df['Material1'].median())
print('Standard Deviation  of Material1 :', df['Material1'].std())
print('Varience of Material1 :', df['Material1'].var())
print('Minimum of Octane :', df['Octane'].min())
print('Maximum of Octane :', df['Octane'].max())

Mean of Material1 : 60.170609756097555
Mode of Material1 : 5.53
Median of Material1 : 62.695
Standard Deviation  of Material1 : 12.43739992552937
Varience of Material1 : 154.68891690755797
Minimum of Octane : 89.66
Maximum of Octane : 97.61

In [ ]:
# mode()[0] gives first mode value from the data

In [ ]:
# to print all mode values
print('Mode of Material1 :', df['Material1'].mode())

Mode of Material1 : 0      4.23
1      5.53
2     17.11
3     44.64
4     44.66
      ...
77    72.30
78    72.66
79    73.13
80    73.74
81    75.54
Name: Material1, Length: 82, dtype: float64

In [ ]:
# Statistical Analysis
df.describe()

          Sample  Material1  Material2  Material3  Condition     Octane
count  82.000000   82.00000  82.000000  82.000000  82.000000  82.000000
mean   41.500000   60.17061   1.663659  55.463415   1.626571  91.849878
std    23.815261   12.43740   1.901952   5.377583   0.219730   1.401124
min     1.000000    4.23000   0.000000  40.000000   1.199750  89.660000
25%    21.250000   55.38000   0.105000  54.000000   1.518095  90.847500
50%    41.500000   62.69500   1.280000  56.000000   1.603575  91.735000
75%    61.750000   67.78000   2.277500  59.750000   1.722818  92.467500
max    82.000000   75.54000  10.760000  64.000000   2.319090  97.610000

In [ ]:
'''
# count -> count of all null values in column
25% is also called as First Quartile Vlaue
50% is also called as Second Quartile Value or more famouslly 'Median'
75% isd also called  as Third Quartile Value
'''

In [ ]:
'''
Conclusions ->
  (1) From 'Material1' column , we can see that Mean is significantly Lesser than median,
  implying that there are outliers in left tail
  (2) From "Material2" column, we can see that mean is significantly greater than median,
  implying that there are outliers in right tail
  (3) From "Material3", "Condition" and "Octane" columns, we can see that mean is approximately equal to median,
  I
'''

In [ ]:
# Importing new dataset
df = pd.read_csv('https://raw.githubusercontent.com/TrainingByPackt/Data-Science-with-Python/master/Chapter01/Data/student.csv',index_col=0)
df.head()

            Age  Gender      Grade Employed
Student_id
1            19    Male  1st Class      yes
2            20  Female  2nd Class       no
3            18    Male  1st Class       no
4            21  Female  2nd Class       no
5            19    Male  1st Class       no

In [ ]:
# Index -> row name

In [ ]:
# Command to include columns of numeric data types only
df_numeric = df.select_dtypes(include = [np.number])
df_numeric.head()

            Age
Student_id
1            19
2            20
3            18
4            21
5            19

In [ ]:
#  Command to exclude columns of numeric data types only
df_cat = df.select_dtypes(exclude = [np.number])
df_cat.head()

            Gender      Grade Employed
Student_id
1             Male  1st Class      yes
2           Female  2nd Class       no
3             Male  1st Class       no
4           Female  2nd Class       no
5             Male  1st Class       no

In [ ]:
# Getting an idea about the unique value in the column
print(df['Grade'].unique())

['1st Class' '2nd Class' '3rd Class']

In [ ]:
# Getting an idea about the number of unique value in the column
print(df['Grade'].nunique())

3

In [ ]:
# Getting the proportion of unique value
print(df['Grade'].value_counts())

Grade
2nd Class    80
3rd Class    80
1st Class    72
Name: count, dtype: int64

In [ ]:
# Getting the percentage of unique value
print(df['Grade'].value_counts(normalize= True))
print(df['Grade'].value_counts(normalize= True) * 100)

Grade
2nd Class    0.344828
3rd Class    0.344828
1st Class    0.310345
Name: proportion, dtype: float64
Grade
2nd Class    34.482759
3rd Class    34.482759
1st Class    31.034483
Name: proportion, dtype: float64

In [ ]:
# Replacing Categorical Values with  Numbers
df['Gender'].replace({'Male' : 0, 'Female' : 1}, inplace = True)
df['Employed'].replace({'no' : 0, 'yes' : 1}, inplace = True)
df['Grade'].replace({'3rd Class' : 1, '2nd Class' : 2, '1st Class' : 3}, inplace = True)
df.head()
print(df)

            Age  Gender  Grade  Employed
Student_id
1            19       0      3         1
2            20       1      2         0
3            18       0      3         0
4            21       1      2         0
5            19       0      3         0
...         ...     ...    ...       ...
228          21       1      3         0
229          20       0      2         0
230          20       0      1         1
231          19       1      3         1
232          20       0      1         1

[232 rows x 4 columns]

<ipython-input-53-41d63d8dbdf8>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].replace({'Male' : 0, 'Female' : 1}, inplace = True)
<ipython-input-53-41d63d8dbdf8>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Gender'].replace({'Male' : 0, 'Female' : 1}, inplace = True)
<ipython-input-53-41d63d8dbdf8>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Employed'].replace({'no' : 0, 'yes' : 1}, inplace = True)
<ipython-input-53-41d63d8dbdf8>:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Employed'].replace({'no' : 0, 'yes' : 1}, inplace = True)
<ipython-input-53-41d63d8dbdf8>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Grade'].replace({'3rd Class' : 1, '2nd Class' : 2, '1st Class' : 3}, inplace = True)
<ipython-input-53-41d63d8dbdf8>:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Grade'].replace({'3rd Class' : 1, '2nd Class' : 2, '1st Class' : 3}, inplace = True)

In [ ]:
# Basic Data Transformation
df = pd.DataFrame(np.array([[1,2,3],
                            [4,5,6],
                            [7,8,9]]), columns= ['a','b','c'])
print(df)

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
# Applying a small transformation
df.transform(func = lambda x : x*10)

    a   b   c
0  10  20  30
1  40  50  60
2  70  80  90

In [ ]:
# Applying a small transformation
df.transform(func = lambda x : np.log(x))

          a         b         c
0  0.000000  0.693147  1.098612
1  1.386294  1.609438  1.791759
2  1.945910  2.079442  2.197225

In [ ]:
# Applying a small transformation exponential
df.transform(func = lambda x : np.exp(x))

             a            b            c
0     2.718282     7.389056    20.085537
1    54.598150   148.413159   403.428793
2  1096.633158  2980.957987  8103.083928

In [ ]:
# Creatin the Dataset
data1 = {
    'Name' : ['Pranav', 'Sai', 'Niraj', 'Vijay'],
    'Age' : [27, 28, 29, 30],
    'Address' : ['Nagpur', 'Kanpur', 'Satara', 'Pune'],
    'Qualification' : ['ME', 'MBA', 'MSc', 'MCA']
}

data2 = {
    'Name' : ['Rahul', 'Ayushi', 'Sharvari', 'Dhiraj'],
    'Age' : [22, 23, 24, 25],
    'Address' : ['Mumbai', 'Delhi', 'Wardha', 'Vizag'],
    'Qualification' : ['BE', 'BTech', 'MSc', 'MA']
}

# Converting to dataframes
df = pd.DataFrame(data1, index = [0, 1, 2, 3])
df1 = pd.DataFrame(data2, index = [4, 5, 6, 7])

print(df, '\n\n', df1)

     Name  Age Address Qualification
0  Pranav   27  Nagpur            ME
1     Sai   28  Kanpur           MBA
2   Niraj   29  Satara           MSc
3   Vijay   30    Pune           MCA

        Name  Age Address Qualification
4     Rahul   22  Mumbai            BE
5    Ayushi   23   Delhi         BTech
6  Sharvari   24  Wardha           MSc
7    Dhiraj   25   Vizag            MA

In [ ]:
# Concatenating the two given dataframes
res = pd.concat([df, df1])
print(res)

       Name  Age Address Qualification
0    Pranav   27  Nagpur            ME
1       Sai   28  Kanpur           MBA
2     Niraj   29  Satara           MSc
3     Vijay   30    Pune           MCA
4     Rahul   22  Mumbai            BE
5    Ayushi   23   Delhi         BTech
6  Sharvari   24  Wardha           MSc
7    Dhiraj   25   Vizag            MA

In [ ]:
# Creatin the Dataset
data1 = {
    'Name' : ['Pranav', 'Sai', 'Niraj', 'Vijay'],
    'Age' : [27, 28, 29, 30],
    'Address' : ['Nagpur', 'Kanpur', 'Satara', 'Pune'],
    'Qualification' : ['ME', 'MBA', 'MSc', 'MCA']
}

data2 = {
    'Name' : ['Rahul', 'Ayushi', 'Sharvari', 'Dhiraj'],
    'Age' : [22, 23, 24, 25],
    'Address' : ['Mumbai', 'Delhi', 'Wardha', 'Vizag'],
    'Qualification' : ['BE', 'BTech', 'MSc', 'MA']
}

# Converting to dataframes
df = pd.DataFrame(data1, index = [0, 1, 2, 3])
df1 = pd.DataFrame(data2, index = [2, 3, 6, 7])

print(df, '\n\n', df1)

     Name  Age Address Qualification
0  Pranav   27  Nagpur            ME
1     Sai   28  Kanpur           MBA
2   Niraj   29  Satara           MSc
3   Vijay   30    Pune           MCA

        Name  Age Address Qualification
2     Rahul   22  Mumbai            BE
3    Ayushi   23   Delhi         BTech
6  Sharvari   24  Wardha           MSc
7    Dhiraj   25   Vizag            MA

In [ ]:
# Concatenating the two given dataframes
res = pd.concat([df, df1])
print(res)

       Name  Age Address Qualification
0    Pranav   27  Nagpur            ME
1       Sai   28  Kanpur           MBA
2     Niraj   29  Satara           MSc
3     Vijay   30    Pune           MCA
2     Rahul   22  Mumbai            BE
3    Ayushi   23   Delhi         BTech
6  Sharvari   24  Wardha           MSc
7    Dhiraj   25   Vizag            MA

In [ ]:
# Creatin the Dataset
data1 = {
    'Name' : ['Pranav', 'Sai', 'Niraj', 'Vijay'],
    'Age' : [27, 28, 29, 30],
}

data2 = {
    'Address' : ['Mumbai', 'Delhi', 'Wardha', 'Vizag'],
    'Qualification' : ['BE', 'BTech', 'MSc', 'MA']
}

# Converting to dataframes
df = pd.DataFrame(data1, index = [0, 1, 2, 3])
df1 = pd.DataFrame(data2, index = [2, 3, 6, 7])

print(df, '\n\n', df1)

     Name  Age
0  Pranav   27
1     Sai   28
2   Niraj   29
3   Vijay   30

   Address Qualification
2  Mumbai            BE
3   Delhi         BTech
6  Wardha           MSc
7   Vizag            MA

In [ ]:
# Column Concatination
res = pd.concat([df, df1], axis = 1)
print(res)

     Name   Age Address Qualification
0  Pranav  27.0     NaN           NaN
1     Sai  28.0     NaN           NaN
2   Niraj  29.0  Mumbai            BE
3   Vijay  30.0   Delhi         BTech
6     NaN   NaN  Wardha           MSc
7     NaN   NaN   Vizag            MA

In [ ]:
'''
axis parameter has only 2 values -> 0 and 1
Default value for axis is 0 -> row wise Concatination
if we manually set axis to 1 -> column wise peration
'''

In [ ]:
#inner join only similer index from  both dataset
res = pd.concat([df, df1], axis = 1, join = 'inner')
print(res)

    Name  Age Address Qualification
2  Niraj   29  Mumbai            BE
3  Vijay   30   Delhi         BTech

In [ ]:
# by default join is set o outer
res = pd.concat([df, df1], axis = 1, join = 'outer')
print(res)

     Name   Age Address Qualification
0  Pranav  27.0     NaN           NaN
1     Sai  28.0     NaN           NaN
2   Niraj  29.0  Mumbai            BE
3   Vijay  30.0   Delhi         BTech
6     NaN   NaN  Wardha           MSc
7     NaN   NaN   Vizag            MA

In [ ]:
'''
Pratise examples with different index values with indexing
'''

# Creatin the Dataset
data1 = {
    'Name' : ['Pranav', 'Sai', 'Niraj', 'Vijay'],
    'Age' : [27, 28, 29, 30],
}

data2 = {
    'Address' : ['Mumbai', 'Delhi', 'Wardha', 'Vizag'],
    'Qualification' : ['BE', 'BTech', 'MSc', 'MA']
}

# Converting to dataframes
df = pd.DataFrame(data1, index = [0, 1, 2, 3])
df1 = pd.DataFrame(data2, index = [2, 3, 6, 7])

print(df, '\n\n', df1)

In [ ]:
# Converting to dataframes
df = pd.DataFrame(data1, index = [0, 1, 2, 3])
df1 = pd.DataFrame(data2, index = [4, 5, 6, 7])

print(df, '\n\n', df1)
# practise
res = pd.concat([df, df1], axis = 1)
print(res)

     Name  Age
0  Pranav   27
1     Sai   28
2   Niraj   29
3   Vijay   30

   Address Qualification
4  Mumbai            BE
5   Delhi         BTech
6  Wardha           MSc
7   Vizag            MA

     Name   Age Address Qualification
0  Pranav  27.0     NaN           NaN
1     Sai  28.0     NaN           NaN
2   Niraj  29.0     NaN           NaN
3   Vijay  30.0     NaN           NaN
4     NaN   NaN  Mumbai            BE
5     NaN   NaN   Delhi         BTech
6     NaN   NaN  Wardha           MSc
7     NaN   NaN   Vizag            MA

In [ ]:
df = pd.DataFrame(data1, index = [0, 1, 2, 3])
df1 = pd.DataFrame(data2, index = [0, 1, 2, 3])

print(df, '\n\n', df1)
# practise
res = pd.concat([df, df1], axis = 1)
print(res)

     Name  Age
0  Pranav   27
1     Sai   28
2   Niraj   29
3   Vijay   30

   Address Qualification
0  Mumbai            BE
1   Delhi         BTech
2  Wardha           MSc
3   Vizag            MA
     Name  Age Address Qualification
0  Pranav   27  Mumbai            BE
1     Sai   28   Delhi         BTech
2   Niraj   29  Wardha           MSc
3   Vijay   30   Vizag            MA